from typing import Any, Dict, List
import pandas as pd
import requests
import snowflake.connector
import streamlit as st
from dotenv import load_dotenv
import os

load_dotenv()


@st.cache_resource
def init_connection():
    try:
        return snowflake.connector.connect(
            user=os.getenv("USER"),
            password=os.getenv("PASSWORD"),
            account=os.getenv("ACCOUNT"),
            warehouse=os.getenv("WAREHOUSE"),
            database=os.getenv("DATABASE"),
            schema=os.getenv("SCHEMA")
        )
    except Exception as e:
        st.error(f"Error connecting to Snowflake: {e}")
        st.stop()


def send_message(prompt: str) -> Dict[str, Any]:
    """Calls the REST API and returns the response."""
    request_body = {
        "messages": [{"role": "user", "content": [{"type": "text", "text": prompt}]}],
        # Removed '@'
        "semantic_view": f"{os.getenv('DATABASE')}.{os.getenv('SCHEMA')}.{os.getenv('SEMANTIC_VIEW')}",
    }
    resp = requests.post(
        url=f"https://{os.getenv('HOST')}/api/v2/cortex/analyst/message",
        json=request_body,
        headers={
            "Authorization": f'Snowflake Token="{st.session_state.CONN.rest.token}"',
            "Content-Type": "application/json",
        },
    )
    request_id = resp.headers.get("X-Snowflake-Request-Id")
    if resp.status_code < 400:
        return {**resp.json(), "request_id": request_id}
    else:
        raise Exception(
            f"Failed request (id: {request_id}) with status {resp.status_code}: {resp.text}"
        )


def process_message(prompt: str) -> None:
    """Processes a message and adds the response to the chat."""
    st.session_state.messages.append(
        {"role": "user", "content": [{"type": "text", "text": prompt}]}
    )
    with st.spinner("Generating response..."):
        response = send_message(prompt=prompt)
        content = response["message"]["content"]
        display_content(content=content)
    st.session_state.messages.append(
        {"role": "assistant", "content": content}
    )


def display_content(content: List[Dict[str, str]]) -> None:
    """Displays only the results from the content."""
    for item in content:
        if item["type"] == "text":
            st.markdown(item["text"])
        elif item["type"] == "sql":
            with st.spinner("Running SQL..."):
                df = pd.read_sql(item["statement"], st.session_state.CONN)
                if len(df.index) > 1:
                    data_tab, line_tab, bar_tab = st.tabs(
                        ["Data", "Line Chart", "Bar Chart"]
                    )
                    data_tab.dataframe(df)
                    if len(df.columns) > 1:
                        df = df.set_index(df.columns[0])
                    with line_tab:
                        st.line_chart(df)
                    with bar_tab:
                        st.bar_chart(df)
                else:
                    st.dataframe(df)

def cortext_analyst():
    # Establish connection
    try:
        st.session_state.CONN = init_connection()
    except Exception as e:
        st.error(f"Failed to initialize connection: {e}")
        st.stop()

    st.title("💬 Cortex Agent")

    # Predefined suggestions
    SUGGESTIONS = [
        "Which store has the highest average sales price?",
        "What are the top 10 products by sales in the Furniture category?",
        "Which brand has the highest sales in Best Buy store?",
        "Which product categories have the highest sales growth over the last 6 months?",
    ]

    # Initialize session state
    if "messages" not in st.session_state:
        st.session_state.messages = []
        st.session_state.suggestions = []
        st.session_state.active_suggestion = None

    if st.button("Clear Chat"):
        st.session_state.messages = []  # Clear all chat history
        st.rerun()

    # Layout for suggestions and results
    with st.container():
        st.subheader("Suggestions")
        for suggestion in SUGGESTIONS:
            if st.button(suggestion, key=f"suggestion_{suggestion}"):
                process_message(prompt=suggestion)

    # Divider to separate suggestions and results
    st.markdown("---")

    # Display chat history and results
    for message in st.session_state.messages:
        display_content(content=message["content"])

    # Chat input for user questions
    if user_input := st.chat_input("What is your question?"):
        process_message(prompt=user_input)
    
    # Add AI disclaimer below the chat input
    st.markdown(
        "<p style='font-size: 12px; color: gray; display: flex; justify-content: center;'>Response generated by AI. Verify accuracy before use.</p>",
        unsafe_allow_html=True,
    )

    # Process active suggestion if any
    if st.session_state.active_suggestion:
        process_message(prompt=st.session_state.active_suggestion)
        st.session_state.active_suggestion = None
